### ISSUE TITLE
add `forge stop / reset` in the steps for forge starter doc

### ISSUE THREAD

**Issue by tyrchen** [ArcBlock/forge-dapp-starters#12]
If user has running forge, or have existing forge data the initialization of the starter may not be expected.

Probably considering to add `forge stop` and `forge reset` in the doc: https://www.npmjs.com/package/forge-next-starter.

**Comment by wangshijun** [comment]
dapp-starters does not require chain reset, what it needs is a running chain and an endpoint that can be connected to.
