### ISSUE TITLE
error when setting up npm

### ISSUE THREAD

**Issue by robroyhobbs** [ArcBlock/forge-dapp-starters#14]
<img width="704" alt="npm-errors" src="https://user-images.githubusercontent.com/41485426/61905925-184ab500-aedf-11e9-96ee-ce1235bfe2c6.png">

followed instructions given 
npm install -g @arcblock/forge-cli forge-react-starter
forge init
forge start
forge create-project hello-forge
cd hello-forge
npm start

when adding npm start received error message that app crashed but still loaded up on browser.  upon completion received the attached message.

**Comment by wangshijun** [comment]
this is because the api server start failed, will fix in another issue https://github.com/ArcBlock/forge-dapp-starters/issues/45
