### ISSUE TITLE
Forge React Starter, incorrect listening port.

### ISSUE THREAD

**Issue by dingpl716** [ArcBlock/forge-dapp-starters#16]
I created a start project by following these instructions:
```
npm install -g @arcblock/forge-cli
forge init
forge start
forge create-project hello-forge
cd hello-forge
yarn start
```

While creating the project, the listening port was set as default value, 3030.
![image](https://user-images.githubusercontent.com/3527426/61906260-cbb3a980-aedf-11e9-9543-e2d22a3a459f.png)

But after I started the project, the server is listening on port 3000 and reported following errors:
![image](https://user-images.githubusercontent.com/3527426/61906372-0b7a9100-aee0-11e9-83a3-2a7d9a5143c9.png)

**Comment by wangshijun** [comment]
@dingpl716 there are 2 ports during development:

- api server port: 3030
- react app live reload server: 3000
