### ISSUE TITLE
[next starter] decimal is not used correctly in both wallet and app

### ISSUE THREAD

**Issue by tyrchen** [ArcBlock/forge-dapp-starters#17]
Wallet seems hardcoded the decimal. It shall be 25 TBA after checkin, and after using 2, it shall be 23 TBA.

![IMG_AC3C4C6EE4B6-1](https://user-images.githubusercontent.com/473888/61906912-374a4680-aee1-11e9-9443-6be998a21c43.jpeg)

app calculated correctly for the checkin - shows 25 TBA, however, when making 2 token purchase to reveal the secret doc, seems app made 0.02 TBA, thus it shows the result as 24.98 TBA.
![snapshot 2019-07-25 下午1 26 46](https://user-images.githubusercontent.com/473888/61906936-403b1800-aee1-11e9-8d80-6f399b6fc5cd.jpg)

**Comment by wangshijun** [comment]
resolved in v0.37.0
