### ISSUE TITLE
Can't login with local starter

### ISSUE THREAD

**Issue by rileyshu53** [ArcBlock/forge-dapp-starters#19]
![image](https://user-images.githubusercontent.com/40574465/61908141-e720b380-aee3-11e9-937f-cb004bf30719.png)

The demo on https://forge-react-starter.netlify.com/ works, but the starter started on local doesn't work.

**Comment by wangshijun** [comment]
should be fixed in latest android and ios version

**Comment by polunzh** [comment]
The dApp starters have been updated a lot so far, and I have not found problem on login.
