### ISSUE TITLE
[keystone starter] sign in with 2 chains with same name will result in 2 accounts in first chain

### ISSUE THREAD

**Issue by sunboshan** [ArcBlock/forge-dapp-starters#20]
Repro step:

1. computer a `forge start`, start a nextjs dapp starter
2. computer b `forge start`, start a keystone dapp starter
3. sign in with computer a's sign-in example
4. sign in with computer b's sign-in example

Expected:
I have two accounts in two chains

Actual:
I have two accounts in one chain

![IMG_10939CB39839-1](https://user-images.githubusercontent.com/4976854/61908323-467ec380-aee4-11e9-9a62-5ae0c02915e0.jpeg)
![IMG_621912367979-1](https://user-images.githubusercontent.com/4976854/61908333-4a124a80-aee4-11e9-958a-4835802a1b55.jpeg)

The second account should be "Keystone.js starter", also it's not reading history data from the correct chain.

**Comment by polunzh** [comment]
Can't reproduce this problem, I test two cases:
1. Two dApps with one chain;
2. Two dApps with different chains;

Both of them has different accounts.
![image](https://user-images.githubusercontent.com/4244426/69927941-f3052d80-14f4-11ea-82d2-c1cd037a35b2.png)
![image](https://user-images.githubusercontent.com/4244426/69927947-f4cef100-14f4-11ea-960f-63f59bbec21c.png)
![image](https://user-images.githubusercontent.com/4244426/69927971-116b2900-14f5-11ea-92e4-fd4beb3cf13f.png)
