### ISSUE TITLE
Front end code with react should become reusable component

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/forge-dapp-starters#24]
Front end code with react should become reusable component, managed by NPM.  Since in Python-starter, React-starter, Gasby-starter, they all looks identical. 

We’d also design the reusable component carefully, so e.g. a pure JS project (without React) can also use some component as dependency.   Zero Server (Zero Framework) can also easily use it as dependency without copy code across many places.

**Comment by wangshijun** [comment]
our ux lib is there: https://arcblock.github.io/ux/

**Comment by wangshijun** [comment]
more components is being added to the lib if we found it resuable.
