### ISSUE TITLE
ArcBlock web boilerplate component

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/forge-dapp-starters#25]
I would wish to have a boilerplate component for me quickly setup a web app with almost 0 code. 

This can also used in those starter projects (#24 ) 

The boilerplate component should be considered a few things: 
- it’s useful, not demo pages (not like starter, but rather a starting point for web front-end dev)
- support OCAP and Forge together as they are all GraphQL 
- support our components (login, payment, etc.)

**Comment by wangshijun** [comment]
our xmark-website-starter did the job
