### ISSUE TITLE
use latest forge javascript sdk and did-auth-protocol

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/forge-dapp-starters#44]
1. api/libs/auth.js: wallet, chainInfo
2. api/routes/auth/payment.js: verify transfer amount
3. api/functions/app.js cleanup
4. yarn start 的时候检查 api server 是否能正常启动，不能直接就退出

**Comment by polunzh** [comment]
Clean up `api/functions/app.js`: https://github.com/ArcBlock/forge-nodejs-server-demo/commit/c9c46f36bb2094f365c8bab0f5263254b4100c21

**Comment by polunzh** [comment]
`yarn start 的时候检查 api server 是否能正常启动，不能直接就退出`:
这个问题产生的原因是`npm-run-all`会同时启动 server 和 client，如果先启动 server 然后启动 client，那么 server 会因为 `nodemon` 的问题无法继续启动 client。
所以从开发角度看，用`npm-run-all`同时启动 server 和 client 不是必须得，所以我就修改为了用两个终端分别启动 server 和 client，任何一个服务有错误抛出都可以看得到。

**Comment by polunzh** [comment]
https://github.com/ArcBlock/forge-dapp-starters/pull/49
