### ISSUE TITLE
We should merge all OCAP starter projects into our big starter project. 

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/forge-dapp-starters#5]
We should merge all OCAP starter projects into our big starter project.  This is more from a product point of view. 

We kind also make “forge” related, “OCAP” related all a kind of dapps, so dapps starter makes sense. 

As a developer, they come to us and see “starter projects” and then they can easily start any of those starter projects.

**Comment by wangshijun** [comment]
close because ocap is sunset
