### ISSUE TITLE
Be able to generate code for starter project from OCAP Playground 

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/forge-dapp-starters#6]
Be able to generate code for starter project from OCAP playground. 

Just make it super easy by generate the scaffold project code for the developers.  They can debug and test the code in the playground and then generate it into starter projects and instantly make it working.  All the need to do is provide a better css, page design, and everything deploy to netlify and it works. 

The generated code may need to send to github, or a downloadable zip file.  Those details need to be handled so developers feel really easy.   Or we can intergrated the online version of VSCode. (Near protocol is hosting such online IDE and make people think they did a lot)

**Comment by wangshijun** [comment]
close because ocap is sunset
