### ISSUE TITLE
Release Version fetch error

### ISSUE THREAD

**Issue by rutvikrockers** [ArcBlock/forge-dapp-starters#61]
Hello,

When i fire **forge install** command in my terminal i got this error:
![Screenshot 2020-03-12 at 6 23 35 PM](https://user-images.githubusercontent.com/31954734/76523874-26117280-648f-11ea-99e4-070e66b5aa8e.png)
Can you please help me with this?

**Comment by mave99a** [comment]
fixed, thanks!
